workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set gradlew permissions
        script: |
          cd Android
          chmod +x ./gradlew
      - name: Build debug APK
        script: |
          cd Android
          ./gradlew assembleDebug
    artifacts:
      - Android/app/build/outputs/**/*.apk
